upgrade duckdb (#113)
* upgrade duckdb

* cleanup

* fix fmt

* fix clippy

* add circe

* fix

* fix

* fix

* adjust atlas function

* auto load ext

* fix fmt

diff --git a/Dockerfile.trex b/Dockerfile.trex
--- a/Dockerfile.trex
+++ b/Dockerfile.trex
@@ -11,6 +11,7 @@ ARG FEATURES=cli/tracing
 ENV ZERO_AR_DATE=1
 ENV DUCKDB_STATIC_BUILD=1
 ENV LLAMA_CUBLAS=1
+ENV duckdb_version=1.3.2
 
 RUN echo "Platform: $TARGETPLATFORM"
 
@@ -37,11 +38,11 @@ RUN --mount=type=cache,target=/usr/local/cargo/registry,id=${TARGETPLATFORM} \
     #(cargo build --profile ${PROFILE} --workspace || true) && \
     GIT_V_TAG=${GIT_V_VERSION} cargo build --profile ${PROFILE} --features "${FEATURES}" && \
     #cargo strip && \
-    mv /usr/src/trex/target/${PROFILE}/trex /root && \
-    cp /usr/src/trex/target/${PROFILE}/build/circe-rust-wrapper-*/out/libcirce-native.so /root/ || true && \
-    CIRCE_REV=$(grep -A1 'circe.*git.*circe-be' ext/trex/Cargo.toml | grep 'rev' | sed 's/.*rev = "\([^"]*\)".*/\1/' | cut -c1-7) && \
-    cp /usr/local/cargo/git/checkouts/circe-be-*/${CIRCE_REV}*/native-libs/linux-x86_64/libcirce-native.so /root/libcirce-native.so || \
-    echo "Warning: Could not find CIRCE native library for revision $CIRCE_REV"
+    mv /usr/src/trex/target/${PROFILE}/trex /root #&& \
+    #cp /usr/src/trex/target/${PROFILE}/build/circe-rust-wrapper-*/out/libcirce-native.so /root/ || true && \
+    #CIRCE_REV=$(grep -A1 'circe.*git.*circe-be' ext/trex/Cargo.toml | grep 'rev' | sed 's/.*rev = "\([^"]*\)".*/\1/' | cut -c1-7) && \
+    #cp /usr/local/cargo/git/checkouts/circe-be-*/${CIRCE_REV}*/native-libs/linux-x86_64/libcirce-native.so /root/libcirce-native.so || \
+    #echo "Warning: Could not find CIRCE native library for revision $CIRCE_REV"
 
 RUN objcopy --compress-debug-sections \
     --only-keep-debug \
@@ -57,16 +58,26 @@ RUN objcopy --strip-debug \
 FROM builder as ort
 RUN ./scripts/install_onnx.sh $ONNXRUNTIME_VERSION linux $TARGETPLATFORM /root/onnxruntime
 
+FROM ghcr.io/p-hoffmann/duckdb-extension-circe:sha-265ca31 AS duckdb_circe
 
 FROM node:18.20.4-bookworm-slim AS trex-base
+
+ARG DUCKDB_VERSION=1.3.2
+ENV DUCKDB_VERSION=${DUCKDB_VERSION}
+
 RUN apt-get update && apt-get install -y curl libssl-dev libgomp1 libopenblas-dev && rm -rf /var/lib/apt/lists/*
 RUN apt-get remove -y perl && apt-get autoremove -y
 
 COPY --from=builder /root/trex /usr/src/trex
 #COPY --from=builder /root/trex.debug /usr/src/trex.debug
-COPY --from=builder /root/libcirce-native.so /usr/lib/libcirce-native.so
 
 COPY --from=ort /root/onnxruntime/lib/libonnxruntime.so* /usr/lib/
+
+RUN mkdir -p /root/.duckdb/extensions/v${DUCKDB_VERSION}/linux_amd64
+COPY --from=duckdb_circe /extensions/circe.duckdb_extension /root/.duckdb/extensions/v${DUCKDB_VERSION}/linux_amd64/circe.duckdb_extension
+
+#ENV DUCKDB_EXTENSION_DIR=/usr/lib/duckdb/extensions \
+#    DUCKDB_CIRCE_EXTENSION=/usr/lib/duckdb/extensions/circe/circe.duckdb_extension
 
 WORKDIR /usr/src
 
